### ISSUE TITLE
Forbidden 403 when Downloading

### ISSUE THREAD

**Issue by utdrmac** [backtracking/ocamlgraph#102]
http://ocamlgraph.lri.fr/download/ocamlgraph-1.8.8.tar.gz
Forbidden 403

**Comment by bitc0m** [comment]
Confirming the same issue ocamlgraph 1.8.8 package is forbidden 403.

**Comment by utdrmac** [comment]
@backtracking This is blocking progress. Is there a mirror? Can you host on github instead?

**Comment by backtracking** [comment]
This tarball is available on github as well:
https://github.com/backtracking/ocamlgraph/releases/tag/v1.8.8

But I guess most users are experiencing the issue when trying to install ocamlgraph through opam.

**Comment by backtracking** [comment]
Please see issue #103

**Comment by backtracking** [comment]
This is fixed now. Sorry for the inconvenience.
