### ISSUE TITLE
Can ocamlgraph deal with (>= 0) float weighted edges?

### ISSUE THREAD

**Issue by UnixJunkie** [backtracking/ocamlgraph#104]
I would like to be sure before I dive in.
From the documentation, I understand that ocamlgraph can only deal with integer weights.

**Comment by signoles** [comment]
yes you can if you use one of the `*Labeled*` graph datastructure, e.g. [`Imperative.Digraph.ConcreteLabeled`](http://ocamlgraph.lri.fr/doc/Imperative.S.ConcreteLabeled.html). Such datastructures allow the developer to specify its own type carried by every edge.

**Comment by UnixJunkie** [comment]
Ok, thanks a lot.
I feel a little sorry that each time I ask a question about ocamlgraph, my question looks stupid.
I am not used to deal with functor-heavy OCaml code (I write very "flat" code), and ocamlgraph realies heavily on functors.

PS: Say Hi to Huisong!
