### ISSUE TITLE
ocamlgraph.1.8.8 package unavailable from repo

### ISSUE THREAD

**Issue by marcoBros** [backtracking/ocamlgraph#107]
Seems like `ocamlgraph.1.8.8` package is not available anymore.

When trying to 
- install ocamlgraph.1.8.8 from command line `opam install ocamlgraph.1.8.8`
- download package with `curl http://ocamlgraph.lri.fr/download/ocamlgraph-1.8.8.tar.gz`

Package is not found

**Environment**
- opam: 2.0.5
- ocaml: 4.08.1

**Comment by marcoBros** [comment]
Closing as issue do not appears anymore (transitional issue)

**Comment by bkontur** [comment]
it is not working today:
![image](https://user-images.githubusercontent.com/8159517/93513009-7d543c00-f925-11ea-8d8d-e636bebc2d54.png)

**Comment by backtracking** [comment]
There was a power cut at the lab today (someone dug into a cable!) and
some services have not been restarted correctly, including virtual
hosting for ocamlgraph.lri.fr. I've notified the technical staff.

Thanks for pointing this out and our apologies.

--
Jean-Christophe

**Comment by bkontur** [comment]
ok, thanks for the info, 
when do you think it will work?
