### ISSUE TITLE
map_vertex iterates same node multiple times

### ISSUE THREAD

**Issue by anwarmamat** [backtracking/ocamlgraph#110]
I am using Persistent.Digraph.ConcreteLabeled for one my applications. map_vertex is visiting the nodes more than one time.

**Comment by backtracking** [comment]
You're right. If we consider this a bug, this could be fixed by inserting a memo pattern such as
```
    let module H = Hashtbl.Make(V) in
    let vtable = H.create 1024 in
    let f v = try H.find vtable v
              with Not_found -> let v' = f v in H.add vtable v v'; v' in
```
in the code of `map_vertex` (in file `blocks.ml`).

**Comment by backtracking** [comment]
In the meantime, you can use such a workaround on your side, by applying the same memo pattern to the function you are passing to `map_vertex`.
I agree that it would be nicer to have `map_vertex` doing it, but at least that's an immediate fix if this is blocking for you.
