### ISSUE TITLE
find_edge Not_found depricated

### ISSUE THREAD

**Issue by anwarmamat** [backtracking/ocamlgraph#111]
When I compile the code that uses find_edge, it shows
" 
Warning 3: deprecated: Not_found
[since 2018-02] Instead of raising [Not_found], consider using [raise_s] with an
informative error message. 
"

**Comment by backtracking** [comment]
OCamlGraph's functions such as `find_edge` indeed raise `Not_found` to signal a search failure.
This is not different from other such functions from the OCaml standard library, e.g. in `Hashtbl` or `Map`.

My understanding is that you are compiling your code with `Base`, Jane Street's alternative standard library where the use of `Not_found` is considered deprecated.

But I see no problem that is specific to OCamlGraph here.

**Comment by anwarmamat** [comment]
yes, I compile it with Jane Street's Core.
