### ISSUE TITLE
building bytecode libraries ?

### ISSUE THREAD

**Issue by treinen** [backtracking/ocamlgraph#118]
Hello,

graph.cmo is no longer build (I compile with "dune build -pocamlgraph @install"), however that file was build in 1.8.8 before the passage to dune. This is a problem when compiling projects that use ocamlgraph into bytecode, for instance for why 3 "make byte".

-Ralf.

**Comment by backtracking** [comment]
Hi Ralf,
Actually, file `graph.cmo` is built but hidden in `_build/default/src/.graph.objs/byte/`.
It is not installed, though. Do you need it to be installed by `dune`? (yet I don't think this is a good idea)
If you need to patch the `dune` file of OCamlGraph for Debian, you can use the `install` stanza. See
https://dune.readthedocs.io/en/stable/dune-files.html#install

**Comment by treinen** [comment]
Salut Jean-Christophe,

in fact it is not a problem anymore, we have backported from the why3 git repository the commit for compiling why3 with ocamlgraph 2.0.0.

**Comment by backtracking** [comment]
Glad to hear you found a solution! (and apologies for the late answer, by the way)
