### ISSUE TITLE
Save graphs as dot files

### ISSUE THREAD

**Issue by ljlin** [backtracking/ocamlgraph#131]
Dear developer,

I was wondering if there's an API that prints a graph as a dot file (or another general-purpose format that can be rendered by external tools).

Or is it recommended to implement an ad-hoc pretty print via [iter_vertex and iter_edges_e](https://github.com/backtracking/ocamlgraph/blob/726e8d6e31224eb70f75655579da9a374e910b98/src/sig.mli#L169)  instead?

Thanks for your help.

Best.
Jianlin

**Comment by thizanne** [comment]
That exists in the [Graphviz](http://backtracking.github.io/ocamlgraph/ocamlgraph/Graph/Graphviz/index.html) module.
