### ISSUE TITLE
opam ocamlgraph version update

### ISSUE THREAD

**Issue by Fourchaux** [backtracking/ocamlgraph#133]
Doesn't the opam version of ocamlgraph deserve an update? 

Latest version 2.0.0 of 8 oct 2020 - an eternity :)

**Comment by backtracking** [comment]
I've made a new release of OCamlGraph this morning (2.1.0)
Opam's CI is in currently progress: https://github.com/ocaml/opam-repository/pull/24333

**Comment by backtracking** [comment]
Note: This is only the `ocamlgraph` package, not `ocamlgraph_gtk`.
