### ISSUE TITLE
HTTP 403 error code

### ISSUE THREAD

**Issue by psteckler** [backtracking/ocamlgraph#134]
The same issue as reported in #103 has returned.

Another power outage?

**Comment by backtracking** [comment]
Hi,
Sorry for the inconvenience. Looks like ocamlgraph.lri.fr is back.
That being said,the opam packages do not point to this website anymore. And generally speaking, anything related to OCamlGraph shoube now be hosted at github.

**Comment by backtracking** [comment]
FYI, the website `ocamlgraph.lri.fr` does not exist anymore and is now permanently redirected here.
