### ISSUE TITLE
Add the old release tarballs referenced in opam-repository

### ISSUE THREAD

**Issue by dra27** [backtracking/ocamlgraph#140]
opam-repository contains version 1.8.1, 1.8.2, 1.8.3, 1.8.5, 1.8.6, 1.8.7 and 1.8.8 all of which reference a source URL of the form `http://ocamlgraph.lri.fr/download/ocamlgraph-{version}.tar.gz`. These are redirecting to `https://github.com/backtracking/ocamlgraph/download/ocamlgraph-{version}.tar.gz` none of which exist.

It's causing a problem for the opam2web generation tool, which is a little aged and still uses ocamlgraph 1.8.8 🙂

Would it be possible for the original tarballs to be hosted on Releases on the GitHub repo, please? The missing tags can be added with

```sh
GIT_COMMITTER_DATE="Fri Apr 4 13:45:38 2014 +0100" git tag -afm "Release 1.8.5" v1.8.5 e1e2302d144
GIT_COMMITTER_DATE="Wed Apr 17 13:13:22 2013 +0100" git tag -afm "Release 1.8.3" v1.8.3 63a5cbf4c16
GIT_COMMITTER_DATE="Wed May 12 09:53:09 2012 +0100" git tag -afm "Release 1.8.2" v1.8.2 14cd6608425
GIT_COMMITTER_DATE="Mon Oct 17 15:26:50 2011 +0100" git tag -afm "Release 1.8.1" v1.8.1 9e2563f88a8
```

and then the tarballs can be added as release artefacts.

I expect you may have them, but otherwise the tarballs are available at:
- 1.8.1: [`ocamlgraph-1.8.1.tar.gz`](https://raw.githubusercontent.com/dra27/opam-source-archives/ocamlgraph-temp/ocamlgraph-1.8.1.tar.gz) (md5 = `5aa256e9587a6d264d189418230af698`)
- 1.8.2: [`ocamlgraph-1.8.2.tar.gz`](https://raw.githubusercontent.com/dra27/opam-source-archives/ocamlgraph-temp/ocamlgraph-1.8.2.tar.gz) (md5 = `efa4394bc4651c90de443ff61c7477e6`)
- 1.8.3: [`ocamlgraph-1.8.3.tar.gz`](https://raw.githubusercontent.com/dra27/opam-source-archives/ocamlgraph-temp/ocamlgraph-1.8.3.tar.gz) (md5 = `ad2dc42f74c77dae9302c40cf2b5ff86`)
- 1.8.5: [`ocamlgraph-1.8.5.tar.gz`](https://raw.githubusercontent.com/dra27/opam-source-archives/ocamlgraph-temp/ocamlgraph-1.8.5.tar.gz) (md5 = `75dde65bfc3f9b07e795343d369aa84d`)
- 1.8.6: [`ocamlgraph-1.8.6.tar.gz`](https://raw.githubusercontent.com/dra27/opam-source-archives/ocamlgraph-temp/ocamlgraph-1.8.6.tar.gz) (md5 = `afbc24f0e0eb72c2d3eda64b68513e73`)
- 1.8.7: [`ocamlgraph-1.8.7.tar.gz`](https://raw.githubusercontent.com/dra27/opam-source-archives/ocamlgraph-temp/ocamlgraph-1.8.7.tar.gz) (md5 = `e733b8309b9374e89d96e907ecaf4f76`)
- 1.8.8: [`ocamlgraph-1.8.8.tar.gz`](https://raw.githubusercontent.com/dra27/opam-source-archives/ocamlgraph-temp/ocamlgraph-1.8.8.tar.gz) (md5 = `9d71ca69271055bd22d0dfe4e939831a`)

Assuming you were to promote the tags to be releases, is it then possible to change the redirections on ocamlgraph.lri.fr?

- http://ocamlgraph.lri.fr/download/ocamlgraph-1.8.8.tar.gz → https://github.com/backtracking/ocamlgraph/releases/download/v1.8.8/ocamlgraph-1.8.8.tar.gz
- http://ocamlgraph.lri.fr/download/ocamlgraph-1.8.7.tar.gz → https://github.com/backtracking/ocamlgraph/releases/download/v1.8.7/ocamlgraph-1.8.7.tar.gz
- http://ocamlgraph.lri.fr/download/ocamlgraph-1.8.6.tar.gz → https://github.com/backtracking/ocamlgraph/releases/download/v186/ocamlgraph-1.8.6.tar.gz
- http://ocamlgraph.lri.fr/download/ocamlgraph-1.8.5.tar.gz → https://github.com/backtracking/ocamlgraph/releases/download/v1.8.5/ocamlgraph-1.8.5.tar.gz
- http://ocamlgraph.lri.fr/download/ocamlgraph-1.8.3.tar.gz → https://github.com/backtracking/ocamlgraph/releases/download/v1.8.3/ocamlgraph-1.8.3.tar.gz
- http://ocamlgraph.lri.fr/download/ocamlgraph-1.8.2.tar.gz → https://github.com/backtracking/ocamlgraph/releases/download/v1.8.2/ocamlgraph-1.8.2.tar.gz
- http://ocamlgraph.lri.fr/download/ocamlgraph-1.8.1.tar.gz → https://github.com/backtracking/ocamlgraph/releases/download/v1.8.1/ocamlgraph-1.8.1.tar.gz

**Comment by backtracking** [comment]
Hi @dra27,
I'm really sorry for that. The site ocamlgraph.lri.fr is about to be disconnected (the lab LRI does not exist anymore) and yesterday I asked for a redirection (to github). But I totally forgot that opam packages were referring to tarballs on the site and not on github. I'll try to fix that asap, hopefully this afternoon. Sincre apologies.

**Comment by backtracking** [comment]
Many thanks for the tag commands! 
I notice that 1.8.6 is missing; is this intentional?

**Comment by dra27** [comment]
> I'm really sorry for that. 

It's no problem at all - they are old releases, and we can't expect all sites/servers to stay online forever 🙂

> Many thanks for the tag commands! I added the tags and the tarballs to github.

You're very welcome!

> Unfortunately, I'm not able to set up the redirections (from ocamlgraph.lri.fr). So we should update the `opam` files. I can do a PR on `opam-repository` if you wish.

Ah, that's quite fair - in which case, a PR to opam-repository to switch the URLs in the packages would be perfect, thank you!

**Comment by backtracking** [comment]
@dra27 
Done. See https://github.com/ocaml/opam-repository/pull/25099
Hope I did everything right...
Now I should do the same for many other soft of mine hosted at former `lri.fr` URLs :sweat:
