### ISSUE TITLE
[Graphviz.Neato] attribute "Pos" does not implement the "pin" option for a node

### ISSUE THREAD

**Issue by Adrien-No** [backtracking/ocamlgraph#143]
Hello,

I would like to draw beautiful diagrams and choose specificly the position of my nodes (Because it would represent a sort of function, with sources on top and destinations on bottom).
For that there is [the parameter \`Pos](https://ocaml.org/p/ocamlgraph/latest/doc/Graph/Graphviz/NeatoAttributes/index.html#type-vertex.Pos), but only gives an initial position and I suspect the draw to realize other modifications that change the final position.
On the [documentation of neato](https://citeseerx.ist.psu.edu/document?repid=rep1&type=pdf&doi=3ab91c9a004f6642ad534e9a5fb91817f32dd747) they talk about a parameter to pin nodes *(please see picture 1)*, but since Parameter \`Pos in OCaml implementation only waits two floats, we can't give this information.

So my question is : Is there a way to force the final position of a node, and if yes, how to do it ?

Thank you,
Adrien

![image](https://github.com/backtracking/ocamlgraph/assets/75485440/70efeb94-93d6-478b-8e19-c1242c240ab1)

**Comment by backtracking** [comment]
Hi @Adrien-No ,
Thanks for pointing this out. Indeed, this is missing in OCamlGraph.
I guess a conservative and simple solution would be to add another constructor
```
| PosPinned of float * float
```
Would that fit your needs?

**Comment by Adrien-No** [comment]
Yes it would works perfectly I think !
Simply to let you know, I temporarly fixed the problem for me with modifying "manually the .dot file" with a function like that (probably upgradable) :
```ocaml
let pin_dot (file_name: string) =
  (* OCaml lib doesn't support adding parameter `!` for pinning (defining permanent pos), so we add it in the .dot file *)
  let file = open_in_bin file_name in
  let content = really_input_string file (in_channel_length file) in
  let new_content = Str.global_replace (Str.regexp "\", s") ("!\", s") content in (* ugly hack, we should extract x and y, them put them back *)
  close_in file;
  let file = Out_channel.open_bin file_name in
  Out_channel.output_string file new_content;
  close_out file
```
So if it take a bit of time adding and other constructor or if it's not useful for someone else, I can clearly stay with this solution.

**Comment by backtracking** [comment]
Indeed that was a simple way out (and likely to be even a one liner with `sed` or anything like that). Anyway, patching OCamlGraph would be useful I think, especially if one wants to mix pinned and unpinned coordinates. I'm going to make the change right now.
