### ISSUE TITLE
Gmap only available for persistent graphs?

### ISSUE THREAD

**Issue by kentookura** [backtracking/ocamlgraph#148]
Hello,

it seems that the signature of `Gmap` assumes that the target graph is persistent:

https://ocaml.org/p/ocamlgraph/2.1.0/doc/Graph/Gmap/module-type-V_DST/index.html#val-add_vertex

Is there a reason for this limitation?

Thanks!

**Comment by backtracking** [comment]
Hello,
This is to accommodate both persistent and imperative graph data structure, with a signature compatible with that of `Builder` in particular. See https://ocaml.org/p/ocamlgraph/2.1.0/doc/Graph/Builder/index.html 

With imperative graphs, just use functions `add_vertex` and `add_edge_e` that unnecessarily return the graph, and it should be fine.

**Comment by kentookura** [comment]
Great, thanks!
