### ISSUE TITLE
Separate graph creation in the Dominator module

### ISSUE THREAD

**Issue by Drup** [backtracking/ocamlgraph#18]
I'm using a graph who is read-only (https://github.com/Drup/llvmgraph), and I would like to compute dominators on it (to be more precise, provide pre-applied functors). The dominator functor allows to build the subgraph of all dominators, which is not possible with my interface. 

The current implementation define `create` and `add_edge` as `assert false`, but it would be better to put this function in another functor altogether and to allow `dom_graph` to be of a different type.

**Comment by signoles** [comment]
That was a nice suggestion. Done in master branch.
