### ISSUE TITLE
Issue with WEIGHT signature 

### ISSUE THREAD

**Issue by Drup** [backtracking/ocamlgraph#35]
In last version 1.8.6, `Path.WEIGHT` was changed so that `weight` is of type `edge -> t` (which breaks compat in a patch version, seriously ...).

`Prim.WEIGHT`, which used to be the same, was not updated.

Maybe the `WEIGHT` signature should be pulled in `Sig` and standardized ?

**Comment by backtracking** [comment]
You're right, sorry for the mess.
I just followed your suggestion. See commit 5307e91f5c

**Comment by Drup** [comment]
I think we can close now. :)
