### ISSUE TITLE
Decomposition d'un graphe en ses composantes connexes

### ISSUE THREAD

**Issue by UnixJunkie** [backtracking/ocamlgraph#40]
Bonjour,

J'en ai deja eu besoin et ca n'etait pas dans ocamlgraph a l'epoque.
Est-ce que ca serait possible de l'avoir?

Merci,
Francois.

**Comment by Drup** [comment]
http://ocamlgraph.lri.fr/doc/Components.html

**Comment by UnixJunkie** [comment]
Yes, but this is for strongly connected components only, I understand.

**Comment by thizanne** [comment]
I think you can get what you want with something like : 

```
module Undir = struct 
  include YourGraph
  let iter_succ f g v = 
    iter_succ f g v; 
    iter_pred f g v
end

module Connected = Components (Undir)
```

**Comment by UnixJunkie** [comment]
Thanks, that would be cool if something like this was provided in ocamlgraph.

**Comment by backtracking** [comment]
Hi François,

It is pretty simple to get connected components using union-find.
I just added a new functor Components.Undirected to do that.

Could you please check it out and tell me whether it fits your needs?

--
Jean-Christophe

**Comment by UnixJunkie** [comment]
I will test it soon, thanks !

**Comment by yakobowski** [comment]
Closing. You can reopen if the module added that Jean-Christophe does not fit your needs.
