### ISSUE TITLE
Is there an equivalent of Graph.Pack.Digraph for persistent graphs?

### ISSUE THREAD

**Issue by UnixJunkie** [backtracking/ocamlgraph#45]
I like a lot Graph.Pack.Digraph because it gives me direct access to all I need.
However, now that I started to do serious things with my graphs, I don't feel
very comfortable that they are mutable, I'd like them to be persistent.

**Comment by Drup** [comment]
`Persistent.Digraph` ? 

Take your destiny in hand, use the functors, luke. :)

**Comment by signoles** [comment]
Graph.Pack is only here for direct access to imperative directed graphs of integers but you have to use the functors in Graph.Imperative or Graph.Persistent for anything else.

**Comment by UnixJunkie** [comment]
OK, thanks !
