### ISSUE TITLE
Can you please release 1.8.7 on OPAM?

### ISSUE THREAD

**Issue by johanneskloos** [backtracking/ocamlgraph#50]
Hi,

Since 1.8.7 has been out for a while, it would be great if we could have it available on OPAM.

Thanks in advance,
Johannes

**Comment by backtracking** [comment]
Hi,

You're right, my mistake.

I've done the pull request and it should be available soon.
Best regards,
--
Jean-Christophe

**Comment by cakeplus** [comment]
This can be closed now. Thanks for the release!
