### ISSUE TITLE
Build error on initial invocation of `make`

### ISSUE THREAD

**Issue by shayne-fletcher** [backtracking/ocamlgraph#53]
This error (Linux - haven't observed on Windows) results on the first invocation of `make`:

```
  File "editor/gen.ml", line 18, characters 0-1:
  Error: Syntax error
```

It's down to some top-level directives at this location in this file. Subsequent invocation of `make` (surprisingly) succeeds.

**Comment by backtracking** [comment]
Surprisingly, I can't reproduce this problem.

It thought it was related to making .depend in the first place, but when
I do "make depend" explicitly, everything is fine (and the arguments of
ocamldep do include editor/gen.ml).

--
Jean-Christophe

**Comment by shayne-fletcher** [comment]
That is a shame. It's super repeatable over here and preventing me from including it into our internal packaging system :( I didn't look closely at the code : maybe the top-level directives could just come out?

**Comment by shayne-fletcher** [comment]
That is a shame. It's super repeatable over here and preventing me from including it into our internal packaging system :( I didn't look closely at the code : maybe the top-level directives could just come out?

**Comment by shayne-fletcher** [comment]
I can try a procedure like ./configure&&make depend&& make. I'll report back.

**Comment by backtracking** [comment]
After a bit of investigation, it seems that this file was nothing more
than a quick file for making interactive tests. So I simply removed it.

Please let me know if your build issues persist.

--
Jean-Christophe

**Comment by shayne-fletcher** [comment]
Certainly. Will do. Thanks!
