### ISSUE TITLE
make check fails with ocaml-4.04.0

### ISSUE THREAD

**Issue by aballier** [backtracking/ocamlgraph#55]
Forward of downstream report: https://bugs.gentoo.org/show_bug.cgi?id=608554

I'm not sure what changed in ocaml-4.04.0... but I reproduced it with git master:

```
$ make check
ocaml graph.cma tests/test_clique.ml tests/check.ml
File "./tests/test_clique.ml", line 3, characters 5-10:
Error: Unbound module Graph
make: *** [Makefile:363: check] Error 2
```

Please let me know if you need any additional information.

**Comment by backtracking** [comment]
You're right, something changed in OCaml that now requires me to add "-I
." to the ocaml command behind "make check". It is fixed.

It may be related to change GPR#591 in
http://caml.inria.fr/pub/distrib/ocaml-4.04/notes/Changes
(marked as an incompatible change) though I'm not sure.

Thanks for reporting it.
--
Jean-Christophe
