### ISSUE TITLE
Compilation fails in OCaml 4.04.0+flambda with lablgtk

### ISSUE THREAD

**Issue by maroneze** [backtracking/ocamlgraph#56]
This is an issue related to lablgtk + flambda, but it manifests itself during compilation of ocamlgraph, so I'm not sure where to report it. I'd like someone to confirm they can reproduce it before filing the bug elsewhere.

In OPAM switch 4.04.0+flambda, with package lablgtk 2.18.5 installed, if I try to install ocamlgraph 1.8.7 from OPAM, or if I try to compile from master (tested with 726e8d6), I get an error:

```
ocamlopt.opt -c -I src -I lib -I /home/user/.opam/4.04.0+flambda/lib/lablgtk2 -I dgraph -I . -for-pack Dgraph dgraph/dGraphView.ml
>> Fatal error: Assignment of a float to a specialised non-float array: (array.unsafe_set[addr]<>
                                                          self/1736
                                                          zoom_f/1701
                                                          Parraysetu_arg/1802)
Fatal error: exception Misc.Fatal_error
Makefile:570: recipe for target 'dgraph/dGraphView.cmx' failed
make: *** [dgraph/dGraphView.cmx] Error 2
```

Could someone please confirm if the issue is reproducible?

Recommendations about where to file the bug (lablgtk or flambda) are also welcome.

By the way, I just tested on 4.05.0+beta2+flambda and there is no issue, so perhaps it was already fixed...

**Comment by yakobowski** [comment]
You should have a look at https://github.com/ocaml/opam-repository/pull/8599, I think this is related.

**Comment by maroneze** [comment]
Ok nothing to see here then (hopefully this might still be useful for non-Frama-C ocamlgraph users).
