### ISSUE TITLE
Fixpoint computes incorrect node labelling

### ISSUE THREAD

**Issue by johanneskloos** [backtracking/ocamlgraph#58]
Hi,

The fixpoint module calculates surprising and (from my understanding) incorrect node labels. 

Consider the [attached](https://github.com/backtracking/ocamlgraph/files/900788/testfix.ml.txt) example. We take the divisor graph (up to 15, but that's arbitrary) and label each node with a set of integers, which initially contains the node label. The fixpoint algorithm is then instantiated to label each node with the union of the label sets of the transitively reachable nodes (i.e., we want to compute all multiples of the node in the graph), by taking set union as the join, set equality as equaity and identity as the transfer function.

_What I would expect:_
The node 10 should be labelled with {10}.
The node 2 should be labelled with {2,4,6,8,10,12,14}.

_What I get:_
The node 10 is labelled with {10}.
The node 2 is labelled with {8, 10, 12, 14}.

Note that a significant part of 2's expected label, including the original label 2, is missing!

A similar errors manifests itself when using forward propagation.

Thanks,
Johannes

**Comment by johanneskloos** [comment]
Further analysis shows that the program above calculates label_v = ⋁ { label_v' | v →* v' is a maximal path }. This is, indeed, correct if all the initial labels are ⊥.

I haven't checked the implementation (yet), but it seems that in a single loop step, we calculate label_v = ⋁ { label_v' | v → v' }, while I expected it to be label_v = label_v ∨ ⋁ { label_v' | v → v' }.

**Comment by eponier** [comment]
I agree with @johanneskloos. Even the `Reachability` given as example in the doc gives strange results (`u` is not reachable from `u` sometimes), that disappear with the alternative definition of `meet` proposed.

**Comment by yakobowski** [comment]
Sorry for the long reaction time on this @thizanne, do you have an opinion on this bug?

**Comment by thizanne** [comment]
I'm a little busy right now but I'll try to look at it. Please ping me next week if I didn't. Meanwhile @eponier if you had a small example of reachability not working as expected that would be nice.

**Comment by eponier** [comment]
Here is an example showing the strange behavior. I did not try to minimize it.

```
module G = Graph.Pack.Digraph
open G

let u0 = V.create 0
let u1 = V.create 1
let u2 = V.create 2
let u3 = V.create 3
let u4 = V.create 4
let u5 = V.create 5
let u6 = V.create 6

let g2 =
  let g2 = create () in
  add_vertex g2 u0;
  add_vertex g2 u1;
  add_vertex g2 u2;
  add_vertex g2 u3;
  add_vertex g2 u4;
  add_vertex g2 u5;
  add_vertex g2 u6;
  add_edge g2 u0 u1;
  add_edge g2 u0 u2;
  add_edge g2 u1 u3;
  add_edge g2 u1 u4;
  add_edge g2 u2 u3;
  add_edge g2 u2 u4;
  add_edge g2 u6 u0;
  add_edge g2 u5 u6;
  add_edge g2 u6 u5;
  add_edge g2 u4 u5;
  add_edge g2 u6 u4;
  add_edge g2 u4 u3;
  g2

(* dot_output g2 "graph.dot" *)

module Reachability = Graph.Fixpoint.Make(G)
          (struct
            type vertex = G.E.vertex
            type edge = G.E.t
            type g = G.t
            type data = bool
            let direction = Graph.Fixpoint.Forward
            let equal = (=)
            let join = (||)
            let analyze _ = (fun x -> x)
          end)

let is_root_vertex = V.equal u1

let result = Reachability.analyze is_root_vertex g2
```

All vertices of `g2` except `u3` can reach every vertex of `g2`.
However, evaluating `result` on all vertices from `u0` to `u6` (and even on `u1`) returns `false`.

If `is_root_vertex` is defined as `V.equal u0`, though, then `result` returns always `true`.

**Comment by eponier** [comment]
@thizanne ping

**Comment by eponier** [comment]
@thizanne ping

**Comment by thizanne** [comment]
Thanks for the reminders. I looked at it and I think that, although this is indeed a bug, the right solution is not the one proposed in #69 and that the bug lies in the fact that vertices are added to the worklist even though their predecessor's value didn't change. I'll do some tests and propose an alternative fix.

**Comment by thizanne** [comment]
Final answer in #69.
