### ISSUE TITLE
Safe string support (4.06.0+beta1 compatibility)

### ISSUE THREAD

**Issue by dbuenzli** [backtracking/ocamlgraph#66]
Compilation of ocamlgraph fails on 4.06.0+beta1 due to safe string becoming the default. 

It seems support for safe-string was added in https://github.com/backtracking/ocamlgraph/pull/60 would it please be possible to make a release ? `ocamlgraph` is in the dep cone of `opam` libs which are in turn used by other tools in the eco-system.

```
=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ocamlgraph.1.8.7] found in cache
[opam-core.2.0.0~beta3.1] found in cache
[opam-format.2.0.0~beta3.1] found in cache
[topkg-care.0.9.0] found in cache

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ERROR] The compilation of ocamlgraph failed at "make".

#=== ERROR while compiling ocamlgraph.1.8.7 ===================================#
# command      make
# path         /Users/dbuenzli/.opam/4.06.0+beta1/.opam-switch/build/ocamlgraph.1.8.7
# exit-code    2
# env-file     /Users/dbuenzli/.opam/log/ocamlgraph-37273-0a5907.env
# output-file  /Users/dbuenzli/.opam/log/ocamlgraph-37273-0a5907.out
### output ###
# [...]
# ocamlc.opt -c -I src -I lib -g -dtypes -w +a -w -4 -w -44 -w -50 -w -48 -w -29 lib/unionfind.ml
# ocamlc.opt -c -I src -I lib -g -dtypes -w +a -w -4 -w -44 -w -50 -w -48 -w -29 lib/heap.mli
# ocamlc.opt -c -I src -I lib -g -dtypes -w +a -w -4 -w -44 -w -50 -w -48 -w -29 lib/heap.ml
# ocamlc.opt -c -I src -I lib -g -dtypes -w +a -w -4 -w -44 -w -50 -w -48 -w -29 lib/bitv.mli
# ocamlc.opt -c -I src -I lib -g -dtypes -w +a -w -4 -w -44 -w -50 -w -48 -w -29 lib/bitv.ml
# File "lib/bitv.ml", line 454, characters 27-39:
# Warning 3: deprecated: String.set
# Use Bytes.set instead.
# File "lib/bitv.ml", line 454, characters 27-28:
# Error: This expression has type string but an expression was expected of type
#          bytes
# make: *** [lib/bitv.cmo] Error 2
```

**Comment by gasche** [comment]
@backtracking: as @yakobowski, I would be happy to help make a release happen if you are busy writing JFLA articles (I can submit the opam-repository pull request for example, if you give me the archive or the commit tag). Note that I think #67 is safe and would benefit from being included in the release as well.

**Comment by backtracking** [comment]
Indeed, I'm busy writing articles :-)

I just made a release 1.8.8 (after merging PR #67).

--
Jean-Christophe

**Comment by gasche** [comment]
Should I take care of the opam-repository submission?

**Comment by backtracking** [comment]
Yes please :-)

Jean-Christophe

**Comment by gasche** [comment]
Done: https://github.com/ocaml/opam-repository/pull/10484

Note that I used https://github.com/backtracking/ocamlgraph/archive/v1.8.8.tar.gz as the release URL, rather than http://ocamlgraph.lri.fr/download/ocamlgraph-1.8.8.tar.gz which does not currently exist. (I had to add the `autoconf` step to the build scripts, as is done in the upstream `opam` file but not in the opam-repository file for 1.8.7). I'll send a PR to massage the upstream `opam`  and `INSTALL.adoc` files into a slightly better shape.

**Comment by backtracking** [comment]
> Note that I used
> https://github.com/backtracking/ocamlgraph/archive/v1.8.8.tar.gz as the
> release URL, rather than
> http://ocamlgraph.lri.fr/download/ocamlgraph-1.8.8.tar.gz which does not
> currently exist.

Done now (but pointing to github instead is fine).

--
Jean-Christophe

**Comment by jpdeplaix** [comment]
I opened a PR to take the new archive instead as the two archives are not the same (the github archive requires autoconf as an extra dependency).
https://github.com/ocaml/opam-repository/pull/10487

**Comment by dbuenzli** [comment]
This has been solved. Thanks !
