### ISSUE TITLE
Cannot add edge in simple Persistent module

### ISSUE THREAD

**Issue by jotterbach** [backtracking/ocamlgraph#74]
Hello there,

I'm running into a big of a problem when trying to use the ocamlgraph Persistent module. I create a simple integer based module:

```
module G = Persistent.Graph.Concrete(
  struct
    type t = int
    let equal a b = phys_equal a b
    let compare a b = if a <= b then a else b
    let hash a = a
  end
)
```

and try to create a simple graph using the code

```
>>> let gr = G.add_vertex gr 1;;
val gr : G.t = <abstr>
>>> let gr = G.add_vertex gr 2;;
val gr : G.t = <abstr>
>>> G.is_empty gr;;
- : bool = false
```

But then when trying to add an edge I run into an error:

```
>>> G.add_edge gr 1 2;;
Exception: Not_found.
Raised at file "map.ml", line 131, characters 16-25
Called from file "src/blocks.ml", line 140, characters 52-66
Called from file "src/persistent.ml", line 220, characters 14-32
Called from file "toplevel/toploop.ml", line 180, characters 17-56
```

Any help in debugging this would be highly appreciated.

**Comment by signoles** [comment]
Your function `compare` does not match the expected specification. It should return 0 when `a` and `b` are equal. Using the default `Pervasives.compare` does the job.
