### ISSUE TITLE
Is there a diameter function?

### ISSUE THREAD

**Issue by UnixJunkie** [backtracking/ocamlgraph#79]
I have an undirected graph.
All edge weights are one and there are cycles.
Is there an algorithm implemented to find the diameter of the graph?
I.e. the longest of all shortest-path between any two pair of points from the graph.

**Comment by UnixJunkie** [comment]
the graph has a single connex component, also

**Comment by UnixJunkie** [comment]
Ok, thanks for the reference.
I have used Graph.Path.Johnson(G)(W).all_pairs_shortest_paths in the past, so I could start from that by taking the longest one, but I was wondering if there is no simpler way.

**Comment by backtracking** [comment]
> I have used Graph.Path.Johnson(G)(W).all_pairs_shortest_paths in the
> past, so I could start from that by taking the longest one, but I was
> wondering if there is no simpler way.

I mentioned Bfs because that's precisely simpler than an algorithm for
weighted graphs such as Johnson's.

-- 
Jean-Christophe

**Comment by UnixJunkie** [comment]
Thanks, I'll try it!
