### ISSUE TITLE
Using 'module type of'

### ISSUE THREAD

**Issue by yakobowski** [backtracking/ocamlgraph#81]
Performing 'git grep Map.S' or 'git grep Hashtbl.S' returns a few hits, mostly in the _results_ of some algorithms. See e.g. `ChaoticIteration` for `Map.S` and `Coloring/Path` for `Hashtbl.S`. Those signatures are okay-ish, in the sense that

1) it works
2) it is not optimal, because you do not have the equality between this particular instance of `Map.S` or `Hashtbl.S` and others created on the same keys.

My proposal would be to replace the occurrences of e.g. `Map.S with type key = G.V.t` by `module type of Map.Make(G.V)`, which is strictly more informative. If all instances of `Map.Make` has been called on the same module-paths everywhere, we would get equality of the results thanks to applicative functors.

Trouble is, the notation `module type of` is only available starting from 3.12.1 and onwards, which would force us to drop support for 3.10.2 and 3.11. @backtracking  @signoles  Do you have opinions on such a change?

(BTW, we really encountered this problem in practice, while trying to use `ChaoticIteration`.)

**Comment by signoles** [comment]
I am ok for such a change in the __results__ of algorithms (as you pointed out), and to drop support for 3.10.2 and 3.11.

**Comment by Drup** [comment]
No, please don't do that, it's wrong. Named signatures are there *precisely* so people don't have to use `module type of`. `module type of` is a very problematic construction, whose semantics is undergoing some changes in the typechecker. You should *always* privilege named signatures when possible.

**Comment by yakobowski** [comment]
I'm not sure I'm following you, but maybe I'm missing a construct of the module system. Is there an alternative that would offer the same expressivity as `module type of Map.Make(...)`?

**Comment by Drup** [comment]
If you *really* want to expose that the map is produced with `Map.Make` (even though I'm not sure it's such a good idea), you can do `Map.S with type key = ... and type t = Map.Make(M).t`. 

`module type of` will give you that signature in practice, but for a library such as ocamlgraph, it seems to me that it's preferable to control manually which equalities are exported, instead of letting them be magically inferred.

**Comment by yakobowski** [comment]
I see thanks. I somehow forgot that this gave the same expressivity.

As for myself, I think we _want_ those equalities. The current signatures forces you to copy from an instance of `Map.Make` to another (which is ridiculous inefficient), or to structure all your development around the modules returned by the OCamlGraph functors, which is weird.

**Comment by thizanne** [comment]
To be honest, I kind of regret exposing the Map interface in `ChaoticIteration`. I'd rather retrospectively have the same kind of interface as in `Fixpoint` and return a `node -> computed_result` function.

**Comment by yakobowski** [comment]
I also think this was a mistake. A function with this type would have been fine, but I think the most idiomatic way to do think (at least w.r.t. OCamlGraph's conventions) would have been to take the datastructure to store the result as argument of the functor.

Still, it is not worth breaking compability for this, so let us see if we can improve the current API.
