### ISSUE TITLE
The API of Dominator.Make_graph is inconsistent with OCamlgraph's style

### ISSUE THREAD

**Issue by eponier** [backtracking/ocamlgraph#88]
The `Make_graph` functor takes as an argument a module whose signature is imperative, while it seems to me that it should be the persistent one, so as to allow the users to use it both with imperative and persistent implementations (potentially using `Builder` when necessary).

Is there a reason for this choice? There are not many changes needed to implement my suggestion.

**Comment by backtracking** [comment]
I don't think there is any good reason for that, but rather historical reasons.
The Dominator module was  a late addition, and it's likely that it was built as a mere ingredient into a larger algorithm.

If you are willing to propose a patch that implements your suggestion, you're most welcome.

**Comment by eponier** [comment]
See https://github.com/backtracking/ocamlgraph/pull/89.

**Comment by yakobowski** [comment]
Fixed by #89
