### ISSUE TITLE
Can't install 1.8.8

### ISSUE THREAD

**Issue by nicolasbronstein** [backtracking/ocamlgraph#96]
Here's the output after opam install ocamlgraph:
```
#=== ERROR while compiling ocamlgraph.1.8.8 ===================================#
# context     2.0.3 | linux/x86_64 | ocaml-base-compiler.4.07.1 | git+https://gitlab.com/tezos/opam-repository.git#f42f3d8042d5ad53605fc4907b19140c01bc678b
# path        ~/latest-version/tezos/_opam/.opam-switch/build/ocamlgraph.1.8.8
# command     ~/.opam/opam-init/hooks/sandbox.sh build make
# exit-code   2
# env-file    ~/.opam/log/ocamlgraph-5123-0a5907.env
# output-file ~/.opam/log/ocamlgraph-5123-0a5907.out
### output ###
# Makefile:38: *** missing separator.  Stop.



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ λ build ocamlgraph 1.8.8
└─ 
```

**Comment by yakobowski** [comment]
We will need additional information, this version is working fine for many people. Can you find the Makefile Opam is trying to use, and post it in this issue? Look into `latest-version/tezos/_opam/.opam-switch/build/ocamlgraph.1.8.8``

**Comment by nicolasbronstein** [comment]
Please find attached, thanks!

**Comment by yakobowski** [comment]
Interesting. See line 38:

```
OCAMLVERSION = 4.07.1
/tezos/_opam/lib/ocaml
```

This is expanded from `OCAMLVERSION = @OCAMLVERSION@`, so something went horribly wrong during the execution of `configure`. Do you have a special version of the OCaml compiler? Can you try launching `OCAMLVERSION=`$OCAMLC -v | sed -n -e 's|.*version *\(.*\)$|\1|p' ` by hand? And I'm actually interested in the entire output of `ocamlc -v`.

**Comment by nicolasbronstein** [comment]
Hi!
Sorry for the delayed response, however, I do not have "ocamlc" exposed/installed, it just logs `ocamlc: command not found`

**Comment by yakobowski** [comment]
Hum, interesting (and weird). Do you have `ocamlopt`? Or it may be that you have not added the result of `opam env` to your environment.

**Comment by nicolasbronstein** [comment]
oh wait, I just noted both ocamlc and ocamlopt are available only within the subfolders where the tezos repo is, is that normal? Feels weird...

Some more background, I have two folders sitting at the same level, say `~/tezos/` and `~/latest-version/`, in both folders I have cloned the tezos repo, now, below results:
-----------------------------------------------
`ocamlc -v | sed -n -e 's|.*version *\(.*\)$|\1|p'`
-----------------------------------------------
on `~/tezos/` yields:
`4.07.1`

on `~/latest-version/` yields: 
`4.07.1`
`/tezos/_opam/lib/ocaml`

--------------
`ocamlc -v`
--------------
on `~/tezos/` yields:
`The OCaml compiler, version 4.07.1
Standard library directory: ~/tezos/_opam/lib/ocaml`

on `~/latest-version/` yields: 
`The OCaml compiler, version 4.07.1
Standard library directory: ~/latest-version/tezos/_opam/lib/ocaml`

**Comment by yakobowski** [comment]
Got it: the `sed` regexp is wrong, and will fail when there is `version` somewhere in the patch where the OCaml stdlib is installed. We will have to fix it, but with my knowledge of sed, this will not be instantaneous. And in any case, you will need a new release to benefit from it. In the meantime, use a path which does not contain `version` :weary: .

**Comment by nicolasbronstein** [comment]
oh! what a coincidence! Ok, thanks for your help, I'll try renaming the path and will report back if I run into other issues, otherwise consider it working.
