### ISSUE TITLE
could there be a new release?

### ISSUE THREAD

**Issue by hannesm** [backtracking/ocamlgraph#97]
the last one is from october 2017 (according to https://github.com/backtracking/ocamlgraph/releases), and there has been happening quite a bit (https://github.com/backtracking/ocamlgraph/compare/v1.8.8...master) -- it'd be great to have a release in opam :)

thanks for your work on this library.

**Comment by MisterDA** [comment]
I’d suggest a port to the Dune build system with the new release.

**Comment by hannesm** [comment]
hey, a friendly reminder whether you could release a new version of ocamlgraph. thanks for this package.

**Comment by rgrinberg** [comment]
Another friendly reminder :)

**Comment by backtracking** [comment]
Thanks for the reminder :-)
I'm thinking of switching to dune to make new releases of OCamlGraph easier in the future.
(And that would also move the tarballs on github instead of ocamlgraph.lri.fr.)
I'll try to do that within a few days.

**Comment by hannesm** [comment]
thanks @backtracking, as far as I can tell since #100 is merged (mid-June), ocamlgraph already uses dune :)

**Comment by backtracking** [comment]
thanks; we are working on it with @pascutto

**Comment by backtracking** [comment]
OCamlGraph 2.0.0 is now available via opam. Enjoy!
